"use client";

import { ApolloProvider } from "@apollo/client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClientContext, Client } from "./clientContext";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ApolloProvider client={Client}>
        <body className={`${inter.className} px-48 py-8`}>{children}</body>
      </ApolloProvider>
    </html>
  );
}
